### ISSUE TITLE
Can you add support for "Require Emails Confirmation" ?

### ISSUE THREAD

**Issue by digitalpianism** [digitalpianism/ajaxlogin#2]
"I have this enabled under System menu>Configuration>Customer Configuration

When trying to create an account it appears to hang with this extension when Require Emails Confirmation set to YES.

Other then that! Awesome extension."

**Comment by marshallus** [comment]
Same problem here, with Emails confirmation, account is created but page seems stuck.
error 500 from ajax request : index.php/ajaxlogin/index/create/

**Comment by digitalpianism** [comment]
@marshallus I have fixed this issue in 0.3.1 ;)

**Comment by marshallus** [comment]
quick,efficient. perfect.
